#!/usr/bin/env python3
"""Generate a testbench that matches a design's actual port list.

The generators this replaces emitted a fixed harness wired to
clk/rst/data_in/data_out. That worked for exactly one module -- the built-in
template -- and silently produced an uncompilable testbench for anything a
user uploaded. Here the port list is read out of the RTL (scripts/rtl_parse)
and the harness is built from it: real widths, real directions, real reset
polarity.

What the generated testbench can and cannot do is worth being explicit
about. It cannot check functional correctness, because nothing here knows
what the design is supposed to compute. What it does is exercise the design
so the rest of the flow has something to work with: hold reset, release it,
drive pseudo-random stimulus on every data input for a fixed number of
cycles, dump a VCD, and report what it observed on the outputs (including
how often they sat at X, which is usually the first sign of an
uninitialised path). It always terminates, which the previous generator's
output did not reliably do.

Usage:
  gen_tb.py <rtl.sv> <out_file> [--lang sv|python] [--top NAME]
                                [--cycles N] [--period NS]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from rtl_parse import (  # noqa: E402
    data_inputs, find_clock, find_reset, parse_sources, ports_by_direction,
)

DEFAULT_CYCLES = 32
DEFAULT_PERIOD_NS = 10
RESET_CYCLES = 3


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def needs_params(module):
    """True when some port width could not be resolved to a constant.

    In that case the testbench declares the design's parameters as localparams
    and reuses the port's own range expression verbatim, rather than guessing a
    width. Guessing here would produce a testbench that compiles and drives the
    wrong number of bits, which is far worse than one that fails to compile.
    """
    return any(port["width"] is None for port in module["ports"])


def sv_range(port):
    """SystemVerilog packed range for a port declaration, or ''."""
    if port["width"] is not None:
        return "" if port["width"] <= 1 else f"[{port['width'] - 1}:0] "
    return f"[{port['msb']}:{port['lsb']}] "


def random_expr(port):
    """An expression yielding a fresh pseudo-random value of the port's width.

    $random is 32 bits wide, so anything wider is built by concatenation --
    assigning a bare $random to a 64-bit port would leave the upper half
    stuck at zero for the whole run and hide half the logic from the VCD.
    """
    width = port["width"]
    if width is None or width <= 32:
        return "$random(seed)"
    chunks = -(-width // 32)  # ceil
    return "{" + ", ".join(["$random(seed)"] * chunks) + "}"


# ---------------------------------------------------------------------------
# SystemVerilog testbench
# ---------------------------------------------------------------------------

def build_sv(module, cycles, period):
    name = module["name"]
    tb_name = f"test_{name}"
    clock = find_clock(module)
    reset = find_reset(module)
    inputs = ports_by_direction(module, "input")
    outputs = ports_by_direction(module, "output")
    inouts = ports_by_direction(module, "inout")
    stim_ports = data_inputs(module)

    out = [
        "`timescale 1ns/1ps",
        "//",
        f"// Auto-generated by scripts/gen_tb.py for module `{name}`.",
        "//",
        "// Exercises the design and dumps a VCD. It does not check functional",
        "// correctness -- the intended behaviour of the design is not known",
        "// here -- so it reports observed output activity instead of asserting",
        "// expected values. Replace the stimulus block to make it self-checking.",
        "//",
        f"module {tb_name};",
        "",
    ]

    if needs_params(module):
        out.append("    // Copied from the design: some port widths depend on these.")
        for param, value in module["params"].items():
            out.append(f"    localparam {param} = {value};")
        out.append("")

    out += [
        f"    localparam integer CLK_PERIOD  = {period};",
        f"    localparam integer STIM_CYCLES = {cycles};",
        f"    localparam integer RESET_CYCLES = {RESET_CYCLES};",
        "",
        "    integer seed = 32'h1234_5678;",
        "    integer i;",
        "    integer x_samples = 0;",
        "    integer samples   = 0;",
        "",
        "    // Design inputs are driven, outputs observed, inouts left floating",
        "    // (an auto-generated harness has no way to know when it may drive a",
        "    // bidirectional pin without contending with the design).",
    ]

    for port in inputs:
        out.append(f"    reg  {sv_range(port)}{port['name']};")
    for port in outputs:
        out.append(f"    wire {sv_range(port)}{port['name']};")
    for port in inouts:
        out.append(f"    wire {sv_range(port)}{port['name']};")
    out.append("")

    # Instantiate with named connections so port order never matters.
    connections = [f".{p['name']}({p['name']})"
                   for p in module["ports"]]
    out.append(f"    {name} dut (")
    out += [f"        {c}," for c in connections[:-1]]
    if connections:
        out.append(f"        {connections[-1]}")
    out.append("    );")
    out.append("")

    if clock:
        out += [
            "    initial " + clock["name"] + " = 1'b0;",
            f"    always #(CLK_PERIOD/2) {clock['name']} = ~{clock['name']};",
            "",
        ]

    # ---- stimulus ----
    out += [
        "    initial begin",
        f'        $dumpfile("{name}.vcd");',
        f"        $dumpvars(0, {tb_name});",
        "",
    ]

    if reset:
        asserted = "1'b0" if reset["active_low"] else "1'b1"
        released = "1'b1" if reset["active_low"] else "1'b0"
        polarity = "active low" if reset["active_low"] else "active high"
        out.append(f"        // Hold {reset['name']} ({polarity}) through startup.")
        out.append(f"        {reset['name']} = {asserted};")

    for port in stim_ports:
        out.append(f"        {port['name']} = {{{port['width'] or 1}{{1'b0}}}};"
                   if port["width"] and port["width"] > 1
                   else f"        {port['name']} = 1'b0;")
    out.append("")

    if clock:
        out.append(f"        repeat (RESET_CYCLES) @(posedge {clock['name']});")
    else:
        out.append("        #(CLK_PERIOD * RESET_CYCLES);")

    if reset:
        out.append(f"        {reset['name']} = {released};")
        if clock:
            out.append(f"        @(posedge {clock['name']});")
        else:
            out.append("        #(CLK_PERIOD);")
    out.append("")

    if stim_ports:
        out.append("        for (i = 0; i < STIM_CYCLES; i = i + 1) begin")
        for port in stim_ports:
            out.append(f"            {port['name']} <= {random_expr(port)};")
        if clock:
            out.append(f"            @(posedge {clock['name']});")
        else:
            out.append("            #(CLK_PERIOD);")
        out.append("        end")
    else:
        out.append("        // No data inputs to drive; just let the design run.")
        if clock:
            out.append(f"        repeat (STIM_CYCLES) @(posedge {clock['name']});")
        else:
            out.append("        #(CLK_PERIOD * STIM_CYCLES);")
    out.append("")

    out += [
        "        // Drain a few more cycles so the last stimulus reaches the outputs.",
    ]
    if clock:
        out.append(f"        repeat (4) @(posedge {clock['name']});")
    else:
        out.append("        #(CLK_PERIOD * 4);")

    out += [
        "",
        f'        $display("[{tb_name}] ran %0d stimulus cycles", STIM_CYCLES);',
    ]
    if outputs:
        out.append(
            f'        $display("[{tb_name}] output samples=%0d, '
            f'samples containing x/z=%0d", samples, x_samples);'
        )
    out.append("        $finish;")
    out.append("    end")
    out.append("")

    # ---- output observation ----
    if outputs:
        out.append("    // Count how often the outputs are undefined. This is reported,")
        out.append("    // not asserted on: a design with uninitialised memory legitimately")
        out.append("    // reads X early on, so failing the run here would be wrong.")
        trigger = (f"@(posedge {clock['name']})" if clock
                   else f"@({' or '.join(p['name'] for p in outputs)})")
        out.append(f"    always {trigger} begin")
        out.append("        samples = samples + 1;")
        reductions = " || ".join(f"(^{p['name']} === 1'bx)" for p in outputs)
        out.append(f"        if ({reductions}) x_samples = x_samples + 1;")
        out.append("    end")
        out.append("")

    out += [
        "    // Hard stop, so a design that never settles cannot hang the flow.",
        "    initial begin",
        "        #(CLK_PERIOD * (STIM_CYCLES + RESET_CYCLES + 64) * 4);",
        f'        $display("[{tb_name}] timeout guard fired");',
        "        $finish;",
        "    end",
        "",
        "endmodule",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# cocotb testbench
# ---------------------------------------------------------------------------

def build_cocotb(module, cycles, period):
    name = module["name"]
    clock = find_clock(module)
    reset = find_reset(module)
    outputs = ports_by_direction(module, "output")
    stim_ports = data_inputs(module)

    lines = [
        '"""Auto-generated by scripts/gen_tb.py for module `%s`.' % name,
        "",
        "Exercises the design so the flow has stimulus and a waveform to work",
        "with. It deliberately does not assert expected output values -- the",
        "intended behaviour of the design is not known here. Add real checks",
        "in place of the observation loop to make this a functional test.",
        '"""',
        "import random",
        "",
        "import cocotb",
        "from cocotb.clock import Clock",
        "from cocotb.triggers import RisingEdge, Timer",
        "",
        f"CLK_PERIOD_NS = {period}",
        f"STIM_CYCLES = {cycles}",
        f"RESET_CYCLES = {RESET_CYCLES}",
        "",
        "# Fixed seed: a failing run has to be reproducible.",
        "SEED = 0x12345678",
        "",
    ]

    # Port width table drives random stimulus ranges.
    if stim_ports:
        lines.append("# Port name -> width in bits, taken from the RTL declaration.")
        lines.append("STIMULUS_PORTS = {")
        for port in stim_ports:
            width = port["width"] if port["width"] else 1
            comment = "" if port["width"] else "  # width unresolved; driven as 1 bit"
            lines.append(f'    "{port["name"]}": {width},{comment}')
        lines.append("}")
        lines.append("")

    # ---- helpers ----
    if clock:
        lines += [
            "async def _start_clock(dut):",
            f'    cocotb.start_soon(Clock(dut.{clock["name"]}, CLK_PERIOD_NS, unit="ns").start())',
            "",
            "",
        ]

    lines += ["async def _reset(dut):"]
    if reset:
        asserted = 0 if reset["active_low"] else 1
        released = 1 if reset["active_low"] else 0
        polarity = "active low" if reset["active_low"] else "active high"
        lines.append(f'    """Hold {reset["name"]} ({polarity}), then release it."""')
        lines.append(f"    dut.{reset['name']}.value = {asserted}")
    else:
        lines.append('    """No reset port on this design; just idle the inputs."""')
    for port in stim_ports:
        lines.append(f"    dut.{port['name']}.value = 0")
    if clock:
        lines.append("    for _ in range(RESET_CYCLES):")
        lines.append(f"        await RisingEdge(dut.{clock['name']})")
    else:
        lines.append("    await Timer(CLK_PERIOD_NS * RESET_CYCLES, unit=\"ns\")")
    if reset:
        lines.append(f"    dut.{reset['name']}.value = {released}")
    if clock:
        lines.append(f"    await RisingEdge(dut.{clock['name']})")
    else:
        lines.append('    await Timer(CLK_PERIOD_NS, unit="ns")')
    lines += ["", ""]

    # ---- reset test ----
    lines += [
        "@cocotb.test()",
        f"async def test_{name}_reset(dut):",
        '    """The design comes out of reset without the simulation dying."""',
    ]
    if clock:
        lines.append("    await _start_clock(dut)")
    lines.append("    await _reset(dut)")
    if outputs:
        lines.append('    dut._log.info("out of reset: " + _sample(dut))')
    else:
        lines.append('    dut._log.info("out of reset")')
    lines += ["", ""]

    # ---- stimulus test ----
    lines += [
        "@cocotb.test()",
        f"async def test_{name}_stimulus(dut):",
        '    """Drive pseudo-random stimulus and report the observed outputs."""',
        "    random.seed(SEED)",
    ]
    if clock:
        lines.append("    await _start_clock(dut)")
    lines.append("    await _reset(dut)")
    lines.append("")
    lines.append("    undefined = 0")
    lines.append("    for _ in range(STIM_CYCLES):")
    if stim_ports:
        lines.append("        for port, width in STIMULUS_PORTS.items():")
        lines.append("            getattr(dut, port).value = random.getrandbits(width)")
    else:
        lines.append("        pass  # no data inputs on this design")
    if clock:
        lines.append(f"        await RisingEdge(dut.{clock['name']})")
    else:
        lines.append('        await Timer(CLK_PERIOD_NS, unit="ns")')
    lines.append('        await Timer(1, unit="ns")  # settle past the edge')
    if outputs:
        lines.append("        if not _is_resolvable(dut):")
        lines.append("            undefined += 1")
    lines.append("")
    lines.append('    dut._log.info(f"ran {STIM_CYCLES} stimulus cycles")')
    if outputs:
        lines.append('    dut._log.info(f"cycles with an undefined output: {undefined}")')
        lines.append("    # Reported, not asserted: uninitialised memory reads X")
        lines.append("    # legitimately, so this must not fail an otherwise good run.")
    lines += ["", ""]

    # ---- observation helpers ----
    if outputs:
        names = ", ".join(f'"{p["name"]}"' for p in outputs)
        lines += [
            f"OUTPUT_PORTS = ({names},)" if len(outputs) == 1
            else f"OUTPUT_PORTS = ({names})",
            "",
            "",
            "def _sample(dut):",
            '    """Render every output as a string, X/Z included."""',
            "    return \", \".join(",
            '        f"{port}={getattr(dut, port).value}" for port in OUTPUT_PORTS',
            "    )",
            "",
            "",
            "def _is_resolvable(dut):",
            '    """True when every output holds a definite 0/1 value."""',
            "    for port in OUTPUT_PORTS:",
            "        try:",
            "            int(getattr(dut, port).value)",
            "        except ValueError:",
            "            return False",
            "    return True",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rtl", nargs="+", help="RTL source file(s)")
    parser.add_argument("out", help="testbench file to write")
    parser.add_argument("--lang", choices=("sv", "python"), default="sv")
    parser.add_argument("--top", default=None, help="top module name")
    parser.add_argument("--cycles", type=int, default=DEFAULT_CYCLES)
    parser.add_argument("--period", type=int, default=DEFAULT_PERIOD_NS)
    args = parser.parse_args()

    parsed = parse_sources(args.rtl, top=args.top)
    module = parsed["top_module"]
    if module is None:
        sys.exit(f"No module found in {', '.join(args.rtl)}")
    if args.top and parsed["top_found"] is False:
        sys.exit(f"Module '{args.top}' not found in {', '.join(args.rtl)}; "
                 f"available: {', '.join(m['name'] for m in parsed['modules'])}")
    if not module["ports"]:
        sys.exit(f"Module '{module['name']}' declares no ports; nothing to drive.")

    builder = build_cocotb if args.lang == "python" else build_sv
    text = builder(module, args.cycles, args.period)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as handle:
        handle.write(text)

    ports = module["ports"]
    print(f"Wrote {args.out}: {args.lang} testbench for '{module['name']}' "
          f"({len(ports)} ports, "
          f"{sum(1 for p in ports if p['direction'] == 'input')} in / "
          f"{sum(1 for p in ports if p['direction'] == 'output')} out)")


if __name__ == "__main__":
    main()
