#!/usr/bin/env python3
"""Generate a default SDC for a design that doesn't ship hand-written
constraints.

Place and route needs timing constraints -- without a create_clock the tool
sees every path as unconstrained, CTS has nothing to build a tree for, and the
timing reports come out empty. Rather than make the user write an SDC for
every design, this derives a reasonable one from the RTL's port list: a clock
on whatever port looks like a clock, I/O delays at 20% of the period, a
driving cell on the inputs and a load on the outputs.

Port extraction is shared with the testbench generator (scripts/rtl_parse), so
an uploaded design is understood the same way by both. That matters for
non-ANSI port headers and parameterised widths, neither of which the previous
inline parser here handled -- it silently returned an empty port list, and the
design then went through place and route with no input constraints at all.

A hand-written constraints/<design>.sdc always wins; the Makefile only calls
this when that file is absent.

Usage: gen_sdc.py <rtl.sv> <design_name> <period_ns> <out.sdc>
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from rtl_parse import parse_sources  # noqa: E402

DRIVING_CELL = "sky130_fd_sc_hd__buf_1"
DRIVING_PIN = "X"
OUTPUT_LOAD_PF = 0.02
IO_DELAY_FRACTION = 0.2


def main():
    if len(sys.argv) != 5:
        sys.exit("usage: gen_sdc.py <rtl.sv> <design_name> <period_ns> <out.sdc>")

    rtl_path, design, period_str, out_path = sys.argv[1:]
    period = float(period_str)

    parsed = parse_sources([rtl_path], top=design)
    module = parsed["top_module"]
    if module is None:
        sys.exit(f"gen_sdc: no module found in {rtl_path}")

    inputs = [p for p in module["ports"] if p["direction"] == "input"]
    clock = next((p for p in inputs if p["is_clock"]), None)
    data_inputs = [p for p in inputs if not p["is_clock"] and not p["is_reset"]]
    resets = [p for p in inputs if p["is_reset"]]

    lines = [
        f"# Auto-generated by scripts/gen_sdc.py for '{module['name']}'.",
        f"# Override by hand-writing constraints/{design}.sdc.",
        "",
        "set_units -time ns -capacitance pF",
        "",
    ]

    if clock:
        io_delay = round(period * IO_DELAY_FRACTION, 3)
        lines += [
            f"create_clock -name core_clk -period {period} [get_ports {clock['name']}]",
            "set_clock_uncertainty 0.25 [get_clocks core_clk]",
            "set_clock_transition 0.15 [get_clocks core_clk]",
            "",
        ]
        if data_inputs:
            ports = " ".join(p["name"] for p in data_inputs)
            lines.append(
                f"set_input_delay -clock core_clk {io_delay} [get_ports {{{ports}}}]"
            )
        lines += [
            f"set_output_delay -clock core_clk {io_delay} [all_outputs]",
            "",
        ]
        if resets:
            # An asynchronous reset is not a timed path in this flow.
            # Constraining it produces violation reports for a path nothing
            # can fix, which buries the real timing results.
            names = " ".join(p["name"] for p in resets)
            lines += [
                "# Asynchronous reset: not a timed path here.",
                f"set_false_path -from [get_ports {{{names}}}]",
                "",
            ]
    else:
        # Purely combinational: no clock to create, but the paths still need a
        # bound or the resizer and the timing reports have nothing to work with.
        lines += [
            "# No clock port found -- constraining the design as combinational.",
            f"set_max_delay {period} -from [all_inputs] -to [all_outputs]",
            "",
        ]

    if data_inputs:
        ports = " ".join(p["name"] for p in data_inputs)
        lines.append(
            f"set_driving_cell -lib_cell {DRIVING_CELL} -pin {DRIVING_PIN} "
            f"[get_ports {{{ports}}}]"
        )
    lines += [
        f"set_load {OUTPUT_LOAD_PF} [all_outputs]",
        "",
    ]

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))

    where = f"clock '{clock['name']}'" if clock else "combinational (no clock port)"
    print(f"Wrote {out_path}: {where}, period {period} ns, "
          f"{len(data_inputs)} data input(s), {len(resets)} reset(s)")


if __name__ == "__main__":
    main()
