"""Auto-generated by scripts/gen_tb.py for module `adder`.

Exercises the design so the flow has stimulus and a waveform to work
with. It deliberately does not assert expected output values -- the
intended behaviour of the design is not known here. Add real checks
in place of the observation loop to make this a functional test.
"""
import random

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

CLK_PERIOD_NS = 10
STIM_CYCLES = 32
RESET_CYCLES = 3

# Fixed seed: a failing run has to be reproducible.
SEED = 0x12345678

# Port name -> width in bits, taken from the RTL declaration.
STIMULUS_PORTS = {
    "a": 4,
    "b": 4,
}

async def _reset(dut):
    """No reset port on this design; just idle the inputs."""
    dut.a.value = 0
    dut.b.value = 0
    await Timer(CLK_PERIOD_NS * RESET_CYCLES, unit="ns")
    await Timer(CLK_PERIOD_NS, unit="ns")


@cocotb.test()
async def test_adder_reset(dut):
    """The design comes out of reset without the simulation dying."""
    await _reset(dut)
    dut._log.info("out of reset: " + _sample(dut))


@cocotb.test()
async def test_adder_stimulus(dut):
    """Drive pseudo-random stimulus and report the observed outputs."""
    random.seed(SEED)
    await _reset(dut)

    undefined = 0
    for _ in range(STIM_CYCLES):
        for port, width in STIMULUS_PORTS.items():
            getattr(dut, port).value = random.getrandbits(width)
        await Timer(CLK_PERIOD_NS, unit="ns")
        await Timer(1, unit="ns")  # settle past the edge
        if not _is_resolvable(dut):
            undefined += 1

    dut._log.info(f"ran {STIM_CYCLES} stimulus cycles")
    dut._log.info(f"cycles with an undefined output: {undefined}")
    # Reported, not asserted: uninitialised memory reads X
    # legitimately, so this must not fail an otherwise good run.


OUTPUT_PORTS = ("sum",)


def _sample(dut):
    """Render every output as a string, X/Z included."""
    return ", ".join(
        f"{port}={getattr(dut, port).value}" for port in OUTPUT_PORTS
    )


def _is_resolvable(dut):
    """True when every output holds a definite 0/1 value."""
    for port in OUTPUT_PORTS:
        try:
            int(getattr(dut, port).value)
        except ValueError:
            return False
    return True
